---
title: "Retro Result Analysis"
params:
  dir: kaluza-hard
output:
  html_notebook:
    code_folding: hide
  pdf_document: default
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---

```{r echo=FALSE}
#=========================================================
# PREAMBLE
#=========================================================

# load the plotting library
suppressMessages(library(ggplot2))
library(grid)
library(gridExtra)
library(tikzDevice)

theme_set(theme_bw())

options(scipen=999)  # turn-off scientific notation like 1e+48

# size of point for scatterplots
POINT_SIZE = 0.5

# timeout
TIMEOUT = 10
TIMEOUT_VAL = 1.05 * TIMEOUT

# FUNCTIONS
read_file <- function(approach) {
  filename = paste0("./", params$dir, "/", approach, "-", params$dir, ".csv")
  df <- read.csv2(filename,
                  header=TRUE,
                  sep=";",
                  comment.char="#",
                  strip.white=TRUE)

  # basic preprocessing
  df <- df[c("Formula", "sat", "time")]

  # deal with timeouts and time type
  df[df == "TO"] <- NA
  df$time <- as.double(as.character(df$time))
  df$time[is.na(df$time)] <- TIMEOUT_VAL
 
  # rename the time column 
  timecol_name = paste0("time.", approach)
  names(df)[names(df) == "time"] <- timecol_name
  
  return(df)
}

merge_dfs <- function(ls) {
  df <- ls[[1]]
  for(i in 2:length(ls)) {
    # TODO: check consistency of results
    df_ls <- ls[[i]]
    
    orig_sat <- df[["sat"]]
    new_sat <- df_ls[["sat"]]
    
    timecol_name <- grep("time.", names(df_ls), value = TRUE)
    df_aux <- df_ls[, c("Formula", timecol_name)]
    
    df <- merge(df, df_aux, by = "Formula")
  }
  return(df)
}
```

```{r echo=FALSE}
df_rmc <- read_file("rmc")
df_rmc_heur <- read_file("rmc_heur")
df_cvc4 <- read_file("cvc4")
df_z3 <- read_file("z3")


df <- merge_dfs(list(df_rmc, df_rmc_heur, df_cvc4, df_z3))

```

These are results of the experiments for Retro:

|                     |                     |
|---------------------|--------------------:|
| **Benchmark**       | `r params$dir`      |
| **Timeout**         | `r TIMEOUT` s       |
| **Benchmarks**      | `r nrow(df)`        |

```{r echo=FALSE}
df
```
```{r echo=FALSE}
rmc_timeout = nrow(df[df$time.rmc == TIMEOUT_VAL,])
rmc_heur_timeout = nrow(df[df$time.rmc_heur == TIMEOUT_VAL,])
cvc4_timeout = nrow(df[df$time.cvc4 == TIMEOUT_VAL,])
z3_timeout = nrow(df[df$time.z3 == TIMEOUT_VAL,])
```
|                      |                     |
|----------------------|--------------------:|
| **RMC timeouts**     | `r rmc_timeout`     |
| **RMC heur timeouts**| `r rmc_heur_timeout`|
| **CVC4 timeouts**    | `r cvc4_timeout`    |
| **Z3 timeouts**      | `r z3_timeout`      |



```{r echo=FALSE}

plot_scatter <- function(df, xlab, ylab) {
  pscat <- ggplot(df, aes_string(x=xlab, y=ylab)) +
    geom_point(size=POINT_SIZE) +
    geom_abline(size=0.1) +
    scale_x_log10() +
    scale_y_log10() +
    theme(axis.text.y = element_text(angle = 90, hjust = 0.5)) +
   # coord_fixed(xlim = c(0.9, TIMEOUT_VAL), ylim = c(0.9, TIMEOUT_VAL)) +
    coord_fixed(xlim = c(0.009, TIMEOUT_VAL), ylim = c(0.009, TIMEOUT_VAL)) +
    labs(
      title="Title",
      subtitle="Subtitle",
      x=xlab,
      y=ylab)
  return(pscat)
}

plot1 <- plot_scatter(df, "time.rmc", "time.cvc4")
plot2 <- plot_scatter(df, "time.rmc_heur", "time.cvc4")

grid.arrange(plot1, plot2, ncol = 2)

plot1 <- plot_scatter(df, "time.rmc", "time.z3")
plot2 <- plot_scatter(df, "time.rmc_heur", "time.z3")

grid.arrange(plot1, plot2, ncol = 2)

plot1 <- plot_scatter(df, "time.cvc4", "time.z3")
plot(plot1)
```

```{r echo=FALSE}

# getting data for cactus plot
get_sorted_col <- function(df, col) {
  time <- df[[col]]
  time <- time[time != TIMEOUT_VAL]
  time <- sort(time)

  df_aux <- as.data.frame(time)
  df_aux$index <- 1:length(df_aux$time)
  
  return(df_aux)
}

# adds a new data set into a cactus plot
add_to_cactus <- function(pcactus, df, col, colour) {
  df_aux <- get_sorted_col(df, col)
  pcactus <- pcactus +
    geom_line(data=df_aux, aes(x=index, y=time, color=colour), na.rm=TRUE) +
    geom_point(data=df_aux, aes(x=index, y=time, color=colour), size=POINT_SIZE, na.rm=TRUE)
  
  return(pcactus)
}


# df_cactus <- get_sorted_col(df, "time.rmc")
# names(df_cactus)[names(df_cactus) == "time"] <- "rmc"
# df_aux <- get_sorted_col(df, "time.cvc4")
# names(df_aux)[names(df_aux) == "time"] <- "cvc4"
# df_cactus <- merge(df_cactus, df_aux, all=TRUE)
# 
# df_aux <- get_sorted_col(df, "time.rmc_heur")
# names(df_aux)[names(df_aux) == "time"] <- "rmc_heur"
# df_cactus <- merge(df_cactus, df_aux, all=TRUE)
# 
# df_aux <- get_sorted_col(df, "time.z3")
# names(df_aux)[names(df_aux) == "time"] <- "z3"
# df_cactus <- merge(df_cactus, df_aux, all=TRUE)
# 
# pcactus <- ggplot(df_cactus, aes(x=index)) +
#   geom_line(aes(y=rmc, color="RMC"), na.rm=TRUE) +
#   geom_line(aes(y=rmc_heur, color="RMC_heur"), na.rm=TRUE) +
#   geom_line(aes(y=cvc4, color="CVC4"), na.rm=TRUE) +
#   geom_line(aes(y=z3, color="Z3"), na.rm=TRUE) #+
#  # scale_color_discrete(name = "Dose", labels = c("RMC", "RMC-heur", "C", "D"))
# 
# 
  


pcactus <- ggplot()

pcactus <- add_to_cactus(pcactus, df, "time.rmc", "RMC")
pcactus <- add_to_cactus(pcactus, df, "time.rmc_heur", "RMC-heur")
pcactus <- add_to_cactus(pcactus, df, "time.cvc4", "CVC4")
pcactus <- add_to_cactus(pcactus, df, "time.z3", "Z3")
# 
# #pcactus <- pcactus + scale_color_manual(name = "Y series", , labels = c("RMC", "RMC-heur", "CVC4", "Z3"))
# pcactus <- pcactus + scale_color_manual(values=c("1"="blue", "2"="red", "3"="green"))
pcactus <- pcactus + labs(
             title="Cactus plot",
             subtitle="Subtitle",
             x="Benchmarks",
             y="Time [s]")
plot(pcactus)



```
